ucgmsim/Empirical_Engine

GMM_models/Bradley_2013_Sa.py
empirical_factory.py

Minor change in empirical_factory

Dependency

---

GMM_models/Bradley_2013_Sa.py
GMM_models/CampbellBozorgina_2012_AI.py
GMM_models/classdef.py
GMM_models/zhou_2006.py
calculate_empirical.py
empirical_factory.py

While I was working on Pre-processing, it turned out that Empirical_Engine had to be also Python3 compliant.

Converted to Python3 compliant

---

empirical/GMM_models/zhou_2006.py

Strings passed in can be numpy strings and this allows them to match as expected

Changed from exact copy check to equivalence check.

---

empirical/GMM_models/Bradley_2010_Sa.py
empirical/scripts/calculate_empirical.py
empirical/scripts/emp_aggregation.py

Temporarily disabled Numba's nopython=True mode to enable automated empirical calculation.
With nopython=True, it runs into numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

Modified to enable autopmated empirical calculation

---

Jenkinsfile
empirical/util/classdef.py
empirical/util/openquake_wrapper.py

I'm guessing this is how the numbering is supposed to work for OQ empiricals?

Add Chao and Phung to empiricals

---

empirical/util/classdef.py
empirical/util/openquake_wrapper.py

Sorry, realised I do want these for my Hikurangi stuff

Add subduction models for Chao and Phung

---

empirical/util/empirical_factory.py
empirical/util/gmpe_params.yaml

Doc on testing:https://wiki.canterbury.ac.nz/display/QuakeCore/Verification+of+GMPE+parameter+entry+config

Gmpe config template

---

Jenkinsfile
requirements.txt

Tested ok : storage footprint is on the knife edge - Need to watch OpenQuake, as it appears to need lots of temp storage during install

Added virt env

---

empirical/util/classdef.py
empirical/util/openquake_wrapper.py

Zhao looks like it needs RTVZ set and Si needs hdepth set.
(have included Tom for adding these to the verification plot set)
(and Joel for context if we are updating the weights)

New OQ models added

---

empirical/GMM_models/McVerry_2006_Sa.py

did a bit more investigation and if this has become an issue, probably passing in garbage data

convert matlab

---

empirical/util/empirical_factory.py

Cherry picking the fix from this PR https://github.com/ucgmsim/Empirical_Engine/pull/82 as the McVerry changes that Robin requested haven't been explictly approved / confirmed in the other PR.

fix to copy the site/fault obj

---

empirical/util/openquake_wrapper_vectorized.py

Now with this script, `openquake_warpper_vectorized`, we can use the following models:
- pSA/PGA/PGV
- Br_13
- ASK_14
- BSSA_14
- CY_14
- Z_06
- P_20
- K_20
- K_20_NZ
- AG_20
- AG_20_NZ
- Ds575/Ds595 
- AS_16
AI with CB_12 will be done via the internal version of CB_12.
CAV with CB_10 will be done via the OQ's CB_08 as they extend CB_08 to have CB_10's CAV. (which needs to be implemented.)
CB_14 changes got merged into OQ's main branch and I just need to implement to pass `estimate_width=True` 
The values don't quite match with existing AS_16 DB due to the way setting the style of faulting(strike-slip, reverse or normal) is different but I compared the paper and OQ's code, and they align nicely.
Hence, I am confident that we can use OQ's AS_16 model for Ds575 and Ds595.(and it is also …

Support AS_16 for Ds575 and Ds595

---

empirical/scripts/calculate_empirical.py
empirical/util/gmm_weights.yaml
empirical/util/openquake_wrapper_vectorized.py

Bradely 2013 does not support the PGV IM

Bradley does not support PGV

---

empirical/scripts/nzshm_residuals.py
empirical/util/classdef.py
empirical/util/openquake_wrapper_vectorized.py

Adding the script and needed models for the NZSHM residual calculation.
Requires oq-engine to have replaced gmsim with https://github.com/GNS-Science/OQ_NZ_SHM_GSIM_LT

Chris NZSHM

---

empirical/scripts/nzshm_residuals.py

Only to compute GMM predictions and residuals for T < Tmax, where Tmax is 1/fmin
fmin is defined as:
f_min = np.sqrt(event_site["f_min_X"] * event_site["f_min_Y"])
if f_min < 0.12:
f_min = 0.099
Results are replaced with nans and are ignored in the MERA
Waiting on https://github.com/ucgmsim/Ancillary-tools/pull/6

Handling fmin mask with nans

---

empirical/scripts/nzshm_residuals.py

Allows users to pass in variables directly into the models using kwargs for period specific adjustments that can be unique per model.

Adding period specific adjustment factors per GMM

---

empirical/util/openquake_wrapper_vectorized.py

Fix dip key error

---

tests/generate_benchmark_outputs.py

This script generates benchmark output data to test Empirical_Engine. It tries to generate pSA, PGA, and PGV for all models and just catches the exceptions caused by some models not supporting PGA or PGV. It has generated 1GB of benchmark data so I've uploaded it to DropBox [here](https://www.dropbox.com/scl/fi/523k3kcdxjks7avz9px46/benchmark_output.zip?rlkey=mpfz6m7zwkjpwgx5ia5whof72&st=knezcqtq&dl=0).

Script to generate benchmark output data for testing

---

oq_wrapper/oq_wrapper/estimations.py

Change to plane areas
Also averages width

Change average to area

---

oq_wrapper/oq_wrapper/constants.py
oq_wrapper/oq_wrapper/examples/run_emp_gmm.py
oq_wrapper/oq_wrapper/wrapper.py

Adds the EAS model for BA18, as well as the required plumbing for EAS models generally.

Add Bayless Abrahamson 2018 model
